import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Saludo from '../components/Saludo.js'
import Video from '@/components/Video.js'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Saludo texto="Este es una video">
          <button>Esto es un boton</button>
         <br></br>
          <span>Esto es un span</span>
          </Saludo>
          <br></br>
          <Video width="400px" height="300px" src="https://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4" ></Video>
       
      </main>
    </>
  )
}
